--ZAD1A
CREATE TABLE A6_LRS (
    GEOM SDO_GEOMETRY
);

--ZAD1B
INSERT INTO A6_LRS
SELECT A.GEOM
FROM STREETS_AND_RAILROADS A, MAJOR_CITIES B
WHERE SDO_RELATE(A.GEOM, SDO_GEOM.SDO_BUFFER(B.GEOM, 10, 1, 'unit=km'), 'mask=ANYINTERACT') = 'TRUE' AND B.CITY_NAME = 'Koszalin';

--ZAD1C
SELECT ROUND(SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km'), 7) AS DISTANCE, ST_LINESTRING(GEOM).ST_NUMPOINTS() AS ST_NUMPOINTS
FROM A6_LRS;

--ZAD1D
UPDATE A6_LRS SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km'));

--ZAD1E
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('A6_LRS', 'GEOM', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
    MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1)),
    8307
);

--ZAD1F
CREATE INDEX A6_LRS_IDX ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

--ZAD2A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) AS VALID_500
FROM A6_LRS;

--ZAD2B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) AS END_PT
FROM A6_LRS;

--ZAD2C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) AS KM150
FROM A6_LRS;

--ZAD2D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) AS CLIPPED
FROM A6_LRS;

--ZAD2E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(A6.GEOM, SDO_LRS.PROJECT_PT(A6.GEOM, C.GEOM)) AS WJAZD_NA_A6
FROM A6_LRS A6, MAJOR_CITIES C WHERE C.CITY_NAME = 'Slupsk';

--ZAD2F
SELECT SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m'), 1, 'unit=km') AS KOSZT
FROM A6_LRS A6, USER_SDO_GEOM_METADATA M
WHERE M.TABLE_NAME = 'A6_LRS' AND M.COLUMN_NAME = 'GEOM';