--ZAD1
CREATE TABLE MOVIES (
    ID NUMBER(12) PRIMARY KEY,
    TITLE VARCHAR2(400) NOT NULL,
    CATEGORY VARCHAR2(50),
    YEAR CHAR(4),
    CAST VARCHAR2(4000),
    DIRECTOR VARCHAR2(4000),
    STORY VARCHAR2(4000),
    PRICE NUMBER(5, 2),
    COVER BLOB,
    MIME_TYPE VARCHAR2(50)
);

--ZAD2
INSERT INTO MOVIES
SELECT ID, TITLE, CATEGORY, SUBSTR(YEAR, 0, 4), CAST, DIRECTOR, STORY, PRICE, IMAGE, MIME_TYPE
FROM DESCRIPTIONS D LEFT JOIN COVERS C ON D.ID = C.MOVIE_ID;

--ZAD3
SELECT ID, TITLE FROM MOVIES WHERE COVER IS NULL;

--ZAD4
SELECT ID, TITLE, DBMS_LOB.GETLENGTH(COVER) AS FILESIZE FROM MOVIES WHERE COVER IS NOT NULL;

--ZAD5
SELECT ID, TITLE, DBMS_LOB.GETLENGTH(COVER) AS FILESIZE FROM MOVIES WHERE COVER IS NULL;

--ZAD6
SELECT DIRECTORY_NAME, DIRECTORY_PATH FROM ALL_DIRECTORIES;

--ZAD7
UPDATE MOVIES SET COVER = EMPTY_BLOB(), MIME_TYPE = 'image/jpeg' WHERE ID = 66;
COMMIT;

--ZAD8
SELECT ID, TITLE, DBMS_LOB.GETLENGTH(COVER) AS FILESIZE FROM MOVIES WHERE ID IN (65, 66);

--ZAD9
DECLARE
    LOBD BLOB;
    FILS BFILE := BFILENAME('ZSBD_DIR', 'escape.jpg');
BEGIN
    SELECT COVER INTO LOBD FROM MOVIES WHERE ID = 66 FOR UPDATE;

    DBMS_LOB.fileopen(FILS, DBMS_LOB.file_readonly);
    DBMS_LOB.LOADFROMFILE(LOBD, FILS, DBMS_LOB.GETLENGTH(FILS));
    DBMS_LOB.FILECLOSE(FILS);

    COMMIT;
END;

--ZAD10
CREATE TABLE TEMP_COVERS (
    MOVIE_ID NUMBER(12),
    IMAGE BFILE,
    MIME_TYPE VARCHAR2(50)
);

--ZAD11
INSERT INTO TEMP_COVERS VALUES (65, BFILENAME('ZSBD_DIR', 'eagles.jpg'), 'image/jpeg');

--ZAD12
SELECT MOVIE_ID, DBMS_LOB.GETLENGTH(IMAGE) AS FILESIZE FROM TEMP_COVERS WHERE MOVIE_ID = 65;

--ZAD13
DECLARE
    LOBD BLOB;
    FILS TEMP_COVERS.IMAGE%TYPE;
    MIME TEMP_COVERS.MIME_TYPE%TYPE;
BEGIN
    SELECT IMAGE, MIME_TYPE INTO FILS, MIME FROM TEMP_COVERS WHERE MOVIE_ID = 65;

    dbms_lob.createtemporary(LOBD, TRUE);

    DBMS_LOB.fileopen(FILS, DBMS_LOB.file_readonly);
    DBMS_LOB.LOADFROMFILE(LOBD, FILS, DBMS_LOB.GETLENGTH(FILS));
    DBMS_LOB.FILECLOSE(FILS);

    UPDATE MOVIES SET COVER = LOBD, MIME_TYPE = MIME WHERE ID = 65;

    dbms_lob.freetemporary(LOBD);

    COMMIT;
END;

--ZAD14
SELECT ID AS MOVIE_ID, DBMS_LOB.GETLENGTH(COVER) AS FILESIZE FROM MOVIES WHERE ID IN (65, 66);

--ZAD15
DROP TABLE MOVIES;
DROP TABLE TEMP_COVERS;