--ZAD1
CREATE TABLE DOKUMENTY (
    ID NUMBER(12) PRIMARY KEY,
    DOKUMENT CLOB
);

--ZAD2
DECLARE
    LOBD CLOB;
    COUNTER INTEGER;
BEGIN
    INSERT INTO DOKUMENTY VALUES(1, EMPTY_CLOB());
    
    SELECT DOKUMENT INTO LOBD FROM DOKUMENTY WHERE ID = 1 FOR UPDATE;
    
    FOR COUNTER IN 1..10000
    LOOP
        DBMS_LOB.APPEND(LOBD, 'Oto tekst. ');
    END LOOP;

    COMMIT;
END;

--ZAD3A
SELECT * FROM DOKUMENTY;

--ZAD3B
SELECT UPPER(DOKUMENT) FROM DOKUMENTY;

--ZAD3C
SELECT LENGTH(DOKUMENT) FROM DOKUMENTY;

--ZAD3D
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;

--ZAD3E
SELECT SUBSTR(DOKUMENT, 5, 1000) FROM DOKUMENTY;

--ZAD3F
SELECT DBMS_LOB.SUBSTR(DOKUMENT, 1000, 5) FROM DOKUMENTY;

--ZAD4
INSERT INTO DOKUMENTY VALUES (2, EMPTY_CLOB());

--ZAD5
INSERT INTO DOKUMENTY VALUES (3, NULL);
COMMIT;

--ZAD6
SELECT * FROM DOKUMENTY;
SELECT UPPER(DOKUMENT) FROM DOKUMENTY;
SELECT LENGTH(DOKUMENT) FROM DOKUMENTY;
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;
SELECT SUBSTR(DOKUMENT, 5, 1000) FROM DOKUMENTY;
SELECT DBMS_LOB.SUBSTR(DOKUMENT, 1000, 5) FROM DOKUMENTY;

--ZAD7
SELECT DIRECTORY_NAME, DIRECTORY_PATH FROM ALL_DIRECTORIES;

--ZAD8
DECLARE
    LOBD CLOB;
    FILS BFILE := BFILENAME('ZSBD_DIR', 'dokument.txt');
    DOFFSET INTEGER := 1;
    SOFFSET INTEGER := 1;
    LANGCTX INTEGER := 0;
    WARN INTEGER := NULL;
BEGIN
    SELECT DOKUMENT INTO LOBD FROM DOKUMENTY WHERE ID = 2 FOR UPDATE;
    
    DBMS_LOB.FILEOPEN(FILS, DBMS_LOB.FILE_READONLY);
    DBMS_LOB.LOADCLOBFROMFILE(LOBD, FILS, DBMS_LOB.LOBMAXSIZE, DOFFSET, SOFFSET, 0, LANGCTX, WARN);
    DBMS_LOB.FILECLOSE(FILS);
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Status operacji: ' || warn);
END;

--ZAD9
UPDATE DOKUMENTY SET DOKUMENT = TO_CLOB(BFILENAME('ZSBD_DIR', 'dokument.txt')) WHERE ID = 3;

--ZAD10
SELECT * FROM DOKUMENTY;

--ZAD11
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;

--ZAD12
DROP TABLE DOKUMENTY;

--ZAD13
CREATE OR REPLACE PROCEDURE CLOB_CENSOR (
    LOBD IN OUT CLOB,
    PATTERN VARCHAR2
) IS
    POSITION INTEGER;
    REPLACE_WITH VARCHAR2(100);
    COUNTER INTEGER;
BEGIN
    FOR COUNTER IN 1..LENGTH(PATTERN) LOOP
        REPLACE_WITH := REPLACE_WITH || '.';
    END LOOP;
    
    LOOP
        POSITION := DBMS_LOB.INSTR(LOBD, PATTERN, 1, 1);
        EXIT WHEN POSITION = 0;
        DBMS_LOB.WRITE(LOBD, LENGTH(PATTERN), POSITION, REPLACE_WITH);
    END LOOP;
END CLOB_CENSOR;

--ZAD14
CREATE TABLE BIOGRAPHIES_COPY AS
SELECT * FROM ZSBD_TOOLS.BIOGRAPHIES;

DECLARE
    LOBD CLOB;
BEGIN
    SELECT BIO INTO LOBD FROM BIOGRAPHIES_COPY WHERE ID = 1 FOR UPDATE;
    
    CLOB_CENSOR(LOBD, 'Cimrman');
    COMMIT;
END;

SELECT * FROM BIOGRAPHIES_COPY;

--ZAD15
DROP TABLE BIOGRAPHIES_COPY;